### ISSUE TITLE
list view unmount issue for IE

### ISSUE THREAD

**Issue by tomwilderspin** [cht8687/react-listview-sticky-header#15]
Just noticed this line in the component unmount: 
https://github.com/cht8687/react-listview-sticky-header/blob/64dfb8374b39851969fe644011b817dd0b96f3e6/src/ReactListView.js#L36

I'm thinking this should be 'detachEvent' ?

**Comment by stevemao** [comment]
I don't thin we support IE. But if you have a easy solution, PR welcome.

**Comment by cht8687** [comment]
@tomwilderspin  I think you are right. that event name seems wrong. welcome to send through PR though. 👍
