### ISSUE TITLE
add why this is better than css position: sticky;

### ISSUE THREAD

**Issue by stevemao** [cht8687/react-listview-sticky-header#2]
`position: sticky;` is quite popular especially on ios sofari.

**Comment by cht8687** [comment]
Firstly, 'position: sticky' is just for making the element fixed position.
you can check in the project file 'ReactListView.js' line 96:

    Object.assign(currentNode.style, this.props.styles.fixedPosition);

this is where I apply the fixed Position to the particular element. 

This project is trying to achieve the sticky effect when there are multiple elements involved. 
You can use 'position:sticky' however, to replace this line of code.  Same thing. But you still need logic to handle the effect.

**Comment by cht8687** [comment]
should you have any more questions let me know. thanks!
