### ISSUE TITLE
sticky title overflows container unlike other titles

### ISSUE THREAD

**Issue by igin** [cht8687/react-listview-sticky-header#3]
<img width="351" alt="screen shot 2015-11-13 at 09 52 50" src="https://cloud.githubusercontent.com/assets/1157516/11142281/619c5bd0-89ec-11e5-9bc1-daf75b35fc64.png">

**Comment by igin** [comment]
Probably the same problem: the sticky title doesn't scroll horizontally if the container gets small and has to scroll horizontally
<img width="359" alt="screen shot 2015-11-13 at 09 54 32" src="https://cloud.githubusercontent.com/assets/1157516/11142327/b87f17c6-89ec-11e5-8479-c271a40c998d.png">

**Comment by cht8687** [comment]
Hi @igin 

Thank you for pointing out this issue.

In the `src/example/Example.js`,  initially, I set the `width` to `40%`, I didn't consider too much about this, as when you use in your project, you may need change the styles sightly to meet your needs. 

But, yes it's a bit confusing and I've changed the CSS sheet a little bit in follow commit:
https://github.com/cht8687/react-listview-sticky-header/commit/93b533efcdd7e01f19993a626a9fab05c36c629a

You can see that:

1. I've reset the initial padding of ul to '0'
2. Change the '40%' to a fixed size. ( 400px, you may change this based on your needs)
3. Resize the `fixedPosition` and `ListHeader` to the same value.

( You can always change the stylesheet to fit your needs)

Now you can see that the issue you listed are gone. 

Should you have any issues let me know. I will try to fix it. Thanks.

**Comment by cht8687** [comment]
@igin  Hi, if you have any more issue related to this, please let me now. I am closing this now. thanks.
