### ISSUE TITLE
flickering effect when scrolling down

### ISSUE THREAD

**Issue by igin** [cht8687/react-listview-sticky-header#4]
when scrolling down the list as soon as there is a new sticky title there is an annoying flickering effect as the new sticky title becomes active. also the first item of the new group is hidden beneath the new sticky title
<img width="355" alt="screen shot 2015-11-13 at 09 58 17" src="https://cloud.githubusercontent.com/assets/1157516/11142366/156bcde4-89ed-11e5-811c-4415b632fefa.png">

**Comment by cht8687** [comment]
Hi @igin , I am investigating this issue.

**Comment by cht8687** [comment]
It appears that the calculations in onScroll function need to be improved. 
I will try to fix it as soon as I can.

**Comment by stevemao** [comment]
Why is this closed @cht8687 ?

**Comment by cht8687** [comment]
@stevemao  this had been fixed in  b6b79e1420bc82d8e12230545127e299fea855b3

**Comment by stevemao** [comment]
:+1:

**Comment by cht8687** [comment]
just spotted there is still a little bit flickering when new section header reaching the fixed position.

**Comment by cht8687** [comment]
This had been fixed, just need adjust last list's height.
